In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/CTA/Datasets/Copy of Titanic-Dataset.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
#for sorrting
fare = df[['Fare']]
print(fare.head())
#creatunbg dataframe pclass and age
class_age = df[['Pclass', 'Age']]
class_age.head()

      Fare
0   7.2500
1  71.2833
2   7.9250
3  53.1000
4   8.0500

   Pclass   Age
0       3  22.0
1       1  38.0
2       3  26.0
3       1  35.0
4       3  35.0

In [ ]:
# Extract 'Survived' and 'Sex' columns
survived_gender = df[['Survived', 'Sex']]
# Displaying the first few rows
survived_gender.head()

   Survived     Sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

In [ ]:
# Filter passengers with Fare > 100
fare_gt_100 =df[df['Fare'] > 100]
# Displaying the result
fare_gt_100.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C

In [ ]:
# Filter passengers in first class (Pclass == 1)
first_class = df[df['Pclass'] == 1]
first_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

In [ ]:
# Filter passengers who are female and under 18
femalebelow18 = df[(df['Age'] < 18) & (df['Sex'] == 'female')]
femalebelow18.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S

In [ ]:
# Filter passengers who embarked at Cherbourg ('C') or Southampton ('S')
embarked_c_or_s = df[df['Embarked'].isin(['C', 'S'])]
embarked_c_or_s.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# Filter passengers in first or second class
first_second_class = df[df['Pclass'].isin([1, 2])]
first_second_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

In [ ]:
# Handling missing values in Age by filling with the median
df['Age'].fillna(df['Age'])
# Add a column fare per year
df['fare_per_year'] = df['Fare'] / df['Age']

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.329545
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.875876
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.304808
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.517143
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.230000

In [ ]:
# Filter for passengers with fare per yearmore than  5
high_fare_age = df[df['fare_per_year'] > 5]

high_fare_age.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,10.537500
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q,14.562500
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,13.842105
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,C,13.859733
50,51,0,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,NaN,S,5.669643

In [ ]:
# Sort by 'fare_per_year' in descending order
agesort = high_fare_age.sort_values(by='fare_per_year', ascending=False)
agesort.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,164.728261
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,75.775000
386,387,0,3,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,NaN,S,46.900000
164,165,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,NaN,S,39.687500
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S,39.000000

In [ ]:
# Add a column
df['fare_per_class'] = df['Fare'] / df['Pclass']
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year,fare_per_class
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.329545,2.416667
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.875876,71.283300
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.304808,2.641667
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.517143,53.100000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.230000,2.683333

In [ ]:
# Filter for male passengers who are adult
adult_males = df[(df['Sex'] == 'male') & (df['Age'] >= 18)]
adult_males.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year,fare_per_class
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.329545,2.416667
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.230000,2.683333
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,0.960417,51.862500
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S,0.402500,2.683333
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S,0.801923,10.425000

In [ ]:
# Sort by 'fare_per_class' in descending order
asd= adult_males.sort_values(by='fare_per_class', ascending=False)

asd.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year,fare_per_class
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,14.637977,512.3292
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,14.231367,512.3292
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,13.842105,263.0000
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,4.109375,263.0000
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C,10.313367,247.5208

In [ ]:
# Select 'Name', 'Age', and 'fare_per_class' columns
result_male_fare = asd[['Name', 'Age', 'fare_per_class']]
result_male_fare.head()

                             Name   Age  fare_per_class
179           Leonard, Mr. Lionel  36.0             0.0
277   Parkes, Mr. Francis "Frank"  28.0             0.0
271  Tornquist, Mr. William Henry  25.0             0.0
263         Harrison, Mr. William  40.0             0.0
732          Knight, Mr. Robert J  28.0             0.0

In [ ]:
#GroupBy Method
#total fare all paasengers are
total_fare =df['Fare'].sum()
print(f"Total Fare: {total_fare}")

Total Fare: 28693.9493

In [ ]:
#total fare for each class
first_class_fare = df[df['Pclass'] == 1]['Fare'].sum()
second_class_fare = df[df['Pclass'] == 2]['Fare'].sum()
third_class_fare = df[df['Pclass'] == 3]['Fare'].sum()

print(f"First Class Fare: {first_class_fare}")
print(f"Second Class Fare: {second_class_fare}")
print(f"Third Class Fare: {third_class_fare}")

First Class Fare: 18177.4125
Second Class Fare: 3801.8417
Third Class Fare: 6714.6951

In [ ]:
#the proportion of total fare revenue for each class
first_class_percentage = (first_class_fare / total_fare) * 100
second_class_percentage = (second_class_fare / total_fare) * 100
third_class_percentage = (third_class_fare / total_fare) * 100

print(f"First Class Fare Percentage: {first_class_percentage:.2f}%")
print(f"Second Class Fare Percentage: {second_class_percentage:.2f}%")
print(f"Third Class Fare Percentage: {third_class_percentage:.2f}%")

First Class Fare Percentage: 63.35%
Second Class Fare Percentage: 13.25%
Third Class Fare Percentage: 23.40%

In [ ]:
import numpy as np
conditions = [
    (df['Age'] < 18),
    (df['Age'] >= 18) & (df['Age'] < 65),
    (df['Age'] >= 65)
]
choices = ['child', 'adult', 'senior']

df['age_group'] =np.select(conditions, choices, default='adult')

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year,fare_per_class,age_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.329545,2.416667,adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.875876,71.283300,adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.304808,2.641667,adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.517143,53.100000,adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.230000,2.683333,adult

In [ ]:
# Count passngers in age group
age_group_counts = df['age_group'].value_counts()

# Total of passengers
total_passengers = len(df)

# Percent for each age group
age_group_percentage = (age_group_counts / total_passengers) * 100

# Show percentage for age groups
age_group_percentage

age_group
adult     86.083053
child     12.682379
senior     1.234568
Name: count, dtype: float64